from __future__ import annotations

from .errors import (
    TaskConfigSaveError,
    TaskDirectoryAlreadyExistsError,
    TaskDirectoryCreationError,
    TaskStorageError,
    TaskWorkspaceDeleteError,
)
from .models import InitializedAnalysisTask, TaskWorkspacePaths
from .names import (
    TASK_NAME_MAX_LENGTH,
    generate_automatic_task_name,
    is_uuid_task_reference,
    normalize_task_reference,
    validate_task_name,
)
from .registry_errors import (
    AnalyticalTaskAlreadyExistsError,
    AnalyticalTaskConfigRevisionError,
    AnalyticalTaskInvalidRecordDataError,
    AnalyticalTaskInvalidTransitionError,
    AnalyticalTaskJobNotFoundError,
    AnalyticalTaskNotFoundError,
    AnalyticalTaskRegistryDatabaseCorruptedError,
    AnalyticalTaskRegistryDatabaseUnavailableError,
    AnalyticalTaskRegistryError,
    AnalyticalTaskRegistryForeignDatabaseError,
    AnalyticalTaskRegistryIncompatibleSchemaError,
    AnalyticalTaskRegistryMigrationError,
    AnalyticalTaskRegistryUnsupportedSchemaVersionError,
    AnalyticalTaskStateConflictError,
    AnalyticalTaskVersionConflictError,
)
from .registry_models import (
    ACTIVE_ANALYTICAL_TASK_JOB_STATES,
    ALLOWED_ANALYTICAL_TASK_TRANSITIONS,
    TERMINAL_ANALYTICAL_TASK_STATES,
    AnalyticalTask,
    AnalyticalTaskJob,
    AnalyticalTaskJobRecord,
    AnalyticalTaskMutationResult,
    AnalyticalTaskMutationResultType,
    AnalyticalTaskRecord,
    AnalyticalTaskSnapshot,
    AnalyticalTaskSortOrder,
    AnalyticalTaskState,
    ExecutionRuntimeLease,
    ExecutionRuntimeLeaseRecord,
)
from .registry_repository import AnalyticalTaskRegistry
from .registry_schema import (
    TASK_JOB_REGISTRY_EXPECTED_COLUMNS,
    TASK_JOB_REGISTRY_TABLE_NAME,
    TASK_REGISTRY_APPLICATION_ID,
    TASK_REGISTRY_EXPECTED_COLUMNS,
    TASK_REGISTRY_EXPECTED_INDEXES,
    TASK_REGISTRY_SCHEMA_VERSION,
    TASK_REGISTRY_TABLE_NAME,
    TASK_RUNTIME_LEASE_REGISTRY_EXPECTED_COLUMNS,
    TASK_RUNTIME_LEASE_REGISTRY_TABLE_NAME,
)
from .registry_service import AnalyticalTaskRegistryService
from .state_machine import AnalyticalTaskLifecycleIntent
from .storage import LocalTaskStorage

__all__ = [
    "ALLOWED_ANALYTICAL_TASK_TRANSITIONS",
    "ACTIVE_ANALYTICAL_TASK_JOB_STATES",
    "TASK_JOB_REGISTRY_EXPECTED_COLUMNS",
    "TASK_JOB_REGISTRY_TABLE_NAME",
    "TASK_REGISTRY_APPLICATION_ID",
    "TASK_REGISTRY_EXPECTED_COLUMNS",
    "TASK_REGISTRY_EXPECTED_INDEXES",
    "TASK_RUNTIME_LEASE_REGISTRY_EXPECTED_COLUMNS",
    "TASK_RUNTIME_LEASE_REGISTRY_TABLE_NAME",
    "TASK_REGISTRY_SCHEMA_VERSION",
    "TASK_REGISTRY_TABLE_NAME",
    "TASK_NAME_MAX_LENGTH",
    "TERMINAL_ANALYTICAL_TASK_STATES",
    "AnalyticalTask",
    "AnalyticalTaskAlreadyExistsError",
    "AnalyticalTaskConfigRevisionError",
    "AnalyticalTaskInvalidRecordDataError",
    "AnalyticalTaskInvalidTransitionError",
    "AnalyticalTaskJob",
    "AnalyticalTaskJobNotFoundError",
    "AnalyticalTaskJobRecord",
    "AnalyticalTaskLifecycleIntent",
    "AnalyticalTaskMutationResult",
    "AnalyticalTaskMutationResultType",
    "AnalyticalTaskNotFoundError",
    "AnalyticalTaskRecord",
    "AnalyticalTaskRegistry",
    "AnalyticalTaskRegistryDatabaseCorruptedError",
    "AnalyticalTaskRegistryDatabaseUnavailableError",
    "AnalyticalTaskRegistryError",
    "AnalyticalTaskRegistryForeignDatabaseError",
    "AnalyticalTaskRegistryIncompatibleSchemaError",
    "AnalyticalTaskRegistryMigrationError",
    "AnalyticalTaskRegistryService",
    "AnalyticalTaskRegistryUnsupportedSchemaVersionError",
    "AnalyticalTaskSortOrder",
    "AnalyticalTaskSnapshot",
    "AnalyticalTaskState",
    "AnalyticalTaskStateConflictError",
    "AnalyticalTaskVersionConflictError",
    "ExecutionRuntimeLease",
    "ExecutionRuntimeLeaseRecord",
    "InitializedAnalysisTask",
    "LocalTaskStorage",
    "TaskConfigSaveError",
    "TaskDirectoryAlreadyExistsError",
    "TaskDirectoryCreationError",
    "TaskStorageError",
    "TaskWorkspaceDeleteError",
    "TaskWorkspacePaths",
    "generate_automatic_task_name",
    "is_uuid_task_reference",
    "normalize_task_reference",
    "validate_task_name",
]
