"use client";

import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type { FormEvent } from "react";
import { useI18n } from "@/components/I18nProvider";
import type { TranslationKey } from "@/lib/i18n";
import { attachTaskToProject, createTask, createUploadSession, deleteUploadItem, getCurrentUser, getProjects, getUploadSession, uploadConfig, uploadInputDirectory, uploadInputFiles } from "@/lib/api/client";
import { toApiClientError, toErrorMessage } from "@/lib/api/errors";
import { getTaskCanonicalPath } from "@/lib/tasks/routing";
import type { AnalysisOverrides, Project, TaskSubmissionRequest, UploadItem, UploadSession } from "@/types/api";

const SESSION_KEY = "jelica.analysis-upload-session";

export function NewTaskForm() {
  const router = useRouter(); const { t } = useI18n();
  const [session, setSession] = useState<UploadSession | null>(null); const [error, setError] = useState<string | null>(null);
  const [name, setName] = useState(""); const [traceId, setTraceId] = useState(""); const [ncbi, setNcbi] = useState<string[]>([""]); const [busy, setBusy] = useState(false); const [progress, setProgress] = useState(0);
  const [projects, setProjects] = useState<Project[]>([]); const [selectedProjectId, setSelectedProjectId] = useState(""); const [authenticated, setAuthenticated] = useState(false); const fileRef = useRef<HTMLInputElement>(null); const folderRef = useRef<HTMLInputElement>(null); const configRef = useRef<HTMLInputElement>(null);
  const [folderSupported, setFolderSupported] = useState(false);
  const [retryFiles, setRetryFiles] = useState<File[]>([]);
  const [alignmentMode, setAlignmentMode] = useState<"" | "compute" | "prealigned" | "none">("");
  const [alignmentConstruction, setAlignmentConstruction] = useState(""); const [mafftStrategy, setMafftStrategy] = useState(""); const [kmerStrand, setKmerStrand] = useState("");
  const [reference, setReference] = useState("");
  const [comparativeEnabled, setComparativeEnabled] = useState(""); const [distanceEnabled, setDistanceEnabled] = useState(""); const [treeEnabled, setTreeEnabled] = useState(""); const [cladeEnabled, setCladeEnabled] = useState("");
  const [kmerText, setKmerText] = useState(""); const [cladeThreshold, setCladeThreshold] = useState("");

  useEffect(() => { let active = true; const id = new URLSearchParams(window.location.search).get("upload") || sessionStorage.getItem(SESSION_KEY); const load = id ? getUploadSession(id) : createUploadSession(); void load.then((value) => { if (!active) return; setSession(value); sessionStorage.setItem(SESSION_KEY, value.id); }).catch(() => { if (active) setSession(null); }); void getCurrentUser().then(() => { if (active) setAuthenticated(true); return getProjects(); }).then((r) => { if (active) setProjects(r.items); }).catch((e) => { if (active && toApiClientError(e).status !== 401) setError(toErrorMessage(e)); }); return () => { active = false; }; }, []);
  useEffect(() => { const input = folderRef.current as (HTMLInputElement & { webkitdirectory?: boolean; directory?: boolean }) | null; if (input) { setFolderSupported("webkitdirectory" in input); input.webkitdirectory = true; input.directory = true; } }, []);

  const addFiles = async (files: File[]) => { if (!session || files.length === 0) return; setBusy(true); setError(null); setProgress(0); try { const response = await uploadInputFiles(session.id, files, setProgress); setRetryFiles([]); setSession({ ...session, items: [...session.items, ...response.items], file_count: session.file_count + response.items.reduce((n, i) => n + i.file_count, 0), total_bytes: session.total_bytes + response.items.reduce((n, i) => n + i.total_bytes, 0) }); } catch (e) { setRetryFiles(files); setError(toErrorMessage(e)); } finally { setBusy(false); } };
  const addFolder = async (files: File[]) => { if (!session || files.length === 0) return; const paths = files.map((f) => (f as File & { webkitRelativePath?: string }).webkitRelativePath || f.name); const root = paths[0].split("/")[0] || t("task.upload.folder"); const relative = paths.map((p) => p.split("/").slice(1).join("/") || p); setBusy(true); setError(null); setProgress(0); try { const item = await uploadInputDirectory(session.id, files, relative, root, setProgress); setSession({ ...session, items: [...session.items, item], file_count: session.file_count + item.file_count, total_bytes: session.total_bytes + item.total_bytes }); } catch (e) { setError(toErrorMessage(e)); } finally { setBusy(false); } };
  const addConfig = async (file: File | undefined) => { if (!session || !file) return; setBusy(true); setError(null); setProgress(0); try { const existing = session.items.find((i) => i.kind === "config_file"); if (existing) await deleteUploadItem(session.id, existing.id); const item = await uploadConfig(session.id, file, setProgress); setSession({ ...session, items: [...session.items.filter((i) => i.kind !== "config_file"), item] }); } catch (e) { setError(toErrorMessage(e)); } finally { setBusy(false); } };
  const remove = async (item: UploadItem) => { if (!session) return; try { await deleteUploadItem(session.id, item.id); setSession({ ...session, items: session.items.filter((i) => i.id !== item.id), file_count: session.file_count - item.file_count, total_bytes: session.total_bytes - item.total_bytes }); } catch (e) { setError(toErrorMessage(e)); } };

  const onSubmit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!session) return; const sources = ncbi.map((s) => s.trim()).filter(Boolean); if (!session.items.some((i) => i.kind !== "config_file") && sources.length === 0) { setError(t("task.upload.no-sources")); return; } const analysis_overrides = buildOverrides(); setBusy(true); setError(null); try { const payload: TaskSubmissionRequest = { upload_session_id: session.id, ncbi_sources: sources, name: name.trim() || null, trace_id: traceId.trim() || null, analysis_overrides }; const task = await createTask(payload); if (selectedProjectId) { try { await attachTaskToProject(selectedProjectId, task.task_id); } catch (e) { setError(`${t("task.project.partial-failure")} ${toErrorMessage(e)}`); return; } } router.push(getTaskCanonicalPath({ task_id: task.task_id, project_id: selectedProjectId || null })); } catch (e) { setError(toErrorMessage(e)); } finally { setBusy(false); } };

  return <form className="form-grid" onSubmit={onSubmit}>
    <section className="upload-source-list"><h2>{t("task.upload.sources")}</h2><div className="actions-row"><button type="button" className="secondary-button" onClick={() => fileRef.current?.click()} disabled={busy}>{t("task.upload.add-files")}</button>{folderSupported ? <button type="button" className="secondary-button" onClick={() => folderRef.current?.click()} disabled={busy}>{t("task.upload.add-folder")}</button> : null}<input ref={fileRef} hidden type="file" multiple onChange={(e) => { void addFiles(Array.from(e.target.files || [])); e.currentTarget.value = ""; }} /><input ref={folderRef} hidden type="file" multiple onChange={(e) => { void addFolder(Array.from(e.target.files || [])); e.currentTarget.value = ""; }} /></div>
      {session?.items.map((item) => <div className="upload-row" key={item.id}><span>{item.display_name} ({item.file_count})</span><button type="button" className="secondary-button" onClick={() => void remove(item)} disabled={busy}>{t("task.upload.remove")}</button></div>)}
      <label className="input-field"><span>{t("task.upload.ncbi")}</span>{ncbi.map((value, index) => <div className="upload-row" key={index}><input value={value} placeholder={t("task.upload.ncbi-placeholder")} onChange={(e) => setNcbi(ncbi.map((v, i) => i === index ? e.target.value : v))} /><button type="button" className="secondary-button" onClick={() => setNcbi(ncbi.filter((_, i) => i !== index))}>{t("task.upload.remove")}</button></div>)}<button type="button" className="secondary-button" onClick={() => setNcbi([...ncbi, ""])}>{t("task.upload.add-ncbi")}</button></label>
      <label className="input-field"><span>{t("task.upload.configuration")}</span><input ref={configRef} hidden type="file" accept=".json,.yaml,.yml" onChange={(e) => { void addConfig(e.target.files?.[0]); e.currentTarget.value = ""; }} /><button type="button" className="secondary-button" onClick={() => configRef.current?.click()} disabled={busy}>{session?.items.some((i) => i.kind === "config_file") ? t("task.upload.replace-config") : t("task.upload.choose-config")}</button></label>
      {busy ? <div className="state-box" role="status">{t("task.upload.uploading")} {progress}%</div> : null}{error ? <div className="state-box state-error" role="alert">{error} {retryFiles.length > 0 ? <button type="button" className="secondary-button" onClick={() => void addFiles(retryFiles)}>{t("task.upload.retry")}</button> : null}</div> : null}
      {session?.submission_status === "consumed" && session.task_id ? <div className="state-box" role="status">{t("task.upload.already-submitted")} <button type="button" className="secondary-button" onClick={() => router.push(getTaskCanonicalPath({ task_id: session.task_id!, project_id: null }))}>{t("task.project.open-task")}</button></div> : null}
    </section>
    <label className="input-field"><span>{t("task.name")}</span><input value={name} onChange={(e) => setName(e.target.value)} /></label>
      <label className="input-field"><span>{t("task.trace-id")}</span><input value={traceId} onChange={(e) => setTraceId(e.target.value)} /></label>
    <fieldset className="form-grid"><legend>{t("task.analysis-settings")}</legend><p>{t("task.analysis-settings-hint")}</p>
      <label className="input-field"><span>{t("task.analysis.alignment-mode")}</span><select value={alignmentMode} onChange={(e) => setAlignmentMode(e.target.value as typeof alignmentMode)}><option value="">{t("task.analysis.inherit")}</option><option value="compute">compute</option><option value="prealigned">prealigned</option><option value="none">none</option></select></label><label className="input-field"><span>{t("task.analysis.alignment-construction")}</span><select value={alignmentConstruction} onChange={(e) => setAlignmentConstruction(e.target.value)}><option value="">{t("task.analysis.inherit")}</option><option value="joint">joint</option><option value="reference_guided">reference_guided</option></select></label><label className="input-field"><span>{t("task.analysis.mafft-strategy")}</span><select value={mafftStrategy} onChange={(e) => setMafftStrategy(e.target.value)}><option value="">{t("task.analysis.inherit")}</option><option value="auto">auto</option><option value="fft_ns_1">fft_ns_1</option><option value="fft_ns_2">fft_ns_2</option><option value="fft_ns_i">fft_ns_i</option><option value="nw_ns_1">nw_ns_1</option><option value="nw_ns_2">nw_ns_2</option><option value="nw_ns_i">nw_ns_i</option></select></label>
      <TriState label={t("task.analysis.comparative")} value={comparativeEnabled} onChange={setComparativeEnabled} t={t} /><TriState label={t("task.analysis.distance")} value={distanceEnabled} onChange={setDistanceEnabled} t={t} /><TriState label={t("task.analysis.tree")} value={treeEnabled} onChange={setTreeEnabled} t={t} /><TriState label={t("task.analysis.clades")} value={cladeEnabled} onChange={setCladeEnabled} t={t} />
      <label className="input-field"><span>{t("task.analysis.kmers")}</span><input value={kmerText} onChange={(e) => setKmerText(e.target.value)} placeholder="AC,CG" /><button type="button" className="secondary-button" onClick={() => setKmerText("")}>{t("task.analysis.reset")}</button></label><label className="input-field"><span>{t("task.analysis.kmer-strand")}</span><select value={kmerStrand} onChange={(e) => setKmerStrand(e.target.value)}><option value="">{t("task.analysis.inherit")}</option><option value="forward">forward</option><option value="reverse_complement">reverse_complement</option><option value="both">both</option></select></label>
      <label className="input-field"><span>{t("task.analysis.reference")}</span><input value={reference} onChange={(e) => setReference(e.target.value)} placeholder={t("task.analysis.reference-placeholder")} /><button type="button" className="secondary-button" onClick={() => setReference("")}>{t("task.analysis.reset")}</button></label>
      <label className="input-field"><span>{t("task.analysis.clade-threshold")}</span><input type="number" min="0" max="1" step="any" value={cladeThreshold} onChange={(e) => setCladeThreshold(e.target.value)} /><button type="button" className="secondary-button" onClick={() => setCladeThreshold("")}>{t("task.analysis.reset")}</button></label>
    </fieldset>
    {authenticated ? <label className="input-field"><span>{t("task.project.label")}</span><select value={selectedProjectId} onChange={(e) => setSelectedProjectId(e.target.value)}><option value="">{t("task.project.none")}</option>{projects.filter((p) => p.status === "active" && ["member", "supervisor"].includes(p.current_user_role || "")).map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label> : null}
    <div className="actions-row"><button type="submit" className="primary-button" disabled={busy || !session || session.submission_status === "consumed"}>{busy ? t("task.upload.submitting") : t("task.action.start")}</button></div>
  </form>;

  function buildOverrides(): AnalysisOverrides | null {
    const result: AnalysisOverrides = {}; if (alignmentMode || alignmentConstruction || mafftStrategy) result.alignment = { ...(alignmentMode ? { mode: alignmentMode as "compute" | "prealigned" | "none" } : {}), ...(alignmentConstruction ? { construction: alignmentConstruction as "joint" | "reference_guided" } : {}), ...(mafftStrategy ? { mafft: { strategy: mafftStrategy as "auto" | "fft_ns_1" | "fft_ns_2" | "fft_ns_i" | "nw_ns_1" | "nw_ns_2" | "nw_ns_i" | "g_ins_i" | "l_ins_i" | "e_ins_i" } } : {}) }; const explicit = (value: string) => value === "" ? undefined : value === "true" ? true : false;
    if (comparativeEnabled) result.comparative_analysis = { enabled: explicit(comparativeEnabled) }; if (distanceEnabled) result.distance_matrix = { enabled: explicit(distanceEnabled) }; if (treeEnabled) result.phylogenetic_tree = { enabled: explicit(treeEnabled) }; if (cladeEnabled || cladeThreshold) result.clade_detection = { ...(cladeEnabled ? { enabled: explicit(cladeEnabled) } : {}), ...(cladeThreshold ? { max_within_clade_distance: Number(cladeThreshold) } : {}) }; if (kmerText.trim() || kmerStrand) result.statistics = { ...(kmerText.trim() ? { kmers: kmerText.split(",").map((v) => v.trim()).filter(Boolean) } : {}), ...(kmerStrand ? { kmer_strand: kmerStrand as "forward" | "reverse_complement" | "both" } : {}) }; if (reference.trim()) result.reference = reference.trim(); return Object.keys(result).length ? result : null;
  }
}

function TriState({ label, value, onChange, t }: { label: string; value: string; onChange: (value: string) => void; t: (key: TranslationKey) => string }) { return <label className="input-field"><span>{label}</span><select value={value} onChange={(e) => onChange(e.target.value)}><option value="">{t("task.analysis.inherit")}</option><option value="true">{t("task.analysis.enabled")}</option><option value="false">{t("task.analysis.disabled")}</option></select><button type="button" className="secondary-button" onClick={() => onChange("")}>{t("task.analysis.reset")}</button></label>; }
